# -*- coding: utf-8 -*-
"""Tugas 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15KlcY0aAXS67RQoHnteDPaxNo7hh_us7

# Simple Password Encryption [Case 1]

Seorang user dari sebuah website ingin meningkatkan security dari password yang dia miliki dengan metode
mengubah password nya menjadi bentuk lain dengan beberapa aturan enkripsi sebagai berikut:
1. Input password bertipe string dengan batasan panjang password 100 karakter
2. Setiap karakter dari string tersebut diubah menjadi ASCII value
3. Kemudian setiap ASCII value tersebut dikembangkan menjadi 3 value dengan dilakukan operasi berikut:
a. Value pertama dibagi dengan integer 26 kemudian dibulatkan dan dijumlahkan dengan 80
kemudian diubah kembali menjadi karakter
b. Value kedua dihitung sisa bagi dengan 26 kemudian dijumlahkan dengan 80 kemudian diubah
kembali menjadi karakter
c. Value ketiga adalah karakter ‘+’ jika value pertama lebih besar dari value kedua, atau value ketiga
adalah karakter ‘-’ jika value pertama tidak lebih besar dari value kedua

4. Deretkan value pertama, kedua dan ketiga untuk setiap karakter dalam password tersebut sehingga
didapatkan password dalam bentuk baru

**a. Bantulah user tersebut dengan membuatkan sebuah program yang secara
otomatis mengubah password yang di input menjadi terenkripsi sesuai aturan
tersebut!**

**b. Apa output yang dihasilkan dari program tersebut jika input password adalah
‘anakanakcerdas2020’ ?**

**c. (Bonus) User tersebut lupa password asli yang dia inputkan ke dalam program
tersebut, password setelah dienkripsi adalah
‘Sc-TV-Sc-TS+T[-Sc-TQ+TV-T[-Sf-Sc-T\-Sc-Qh-Qf-Qh-Qf-TS+Sg-Se-Sg-’.
Bantulah user tersebut mendapatkan password asli nya!**
"""

def encrypt(pwd):
  splitpass = list(pwd)
  asciipass = list()
  for char in splitpass:
    asciichar = ord(char)
    asciipass.append(asciichar)

  np = ""
  for num in asciipass:
    firstval = num//26 + 80
    secondval = num%26 + 80
    if firstval > secondval:
      thirdval = '-'
    else:
      thirdval = '+'
    np = np + chr(firstval) + chr(secondval) + thirdval
  return np

def real_pw(pwd):
  splitpass = [pwd[i:i+3] for i in range(0, len(pwd), 3)]
  asciipass = list()
  for word in splitpass:
    firstval = ord(word[0]) - 80
    secval = ord(word[1]) - 80
    val = 26 * firstval + secval
    asciipass.append(val)
  password = ''
  for i in asciipass:
    char = chr(i)
    password = password + char
  return password

password1 = 'anakanakcerdas2020'
print ('Password Asli : '+ password1)
print ("Encrypt : "+ encrypt(password1))

password2 = "Sc-TV-Sc-TS+T[-Sc-TQ+TV-T[-Sf-Sc-T\-Sc-Qh-Qf-Qh-Qf-TS+Sg-Se-Sg-"
print ("Encrypt : " + password2)
print ("Password Asli : " + real_pw(password2))